
replicaCount: 1

image:
  repository: telemetry-service-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

kafka:
  enabled: true
  bootstrapServers: "kafka:9092"
